name: xMoLang
main: CortexPE\xMoLang\Main
version: 1.0.0
api: 4.0.0
load: POSTWORLD
authors: ["CortexPE", "Spajker7", "TwistedAsylumMC"]
description: Use client-side scripting in PocketMine-MP!
website: https://CortexPE.xyz